-- SCHEMA SAAS MULTI-TENANT (Gabinete Ágil)

-- 1. Cabinets (Gabinetes - Os Tenants do sistema)
CREATE TABLE IF NOT EXISTS public.cabinets (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  plan TEXT CHECK (plan IN ('free', 'pro', 'enterprise')) DEFAULT 'free',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.cabinets ENABLE ROW LEVEL SECURITY;

-- 2. Profiles (Perfil do Usuário)
-- Vincula o usuário da autenticação (auth.users) a um Gabinete específico
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  cabinet_id UUID REFERENCES public.cabinets(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  email TEXT,
  role TEXT CHECK (role IN ('super_admin', 'admin', 'manager', 'staff', 'volunteer')) DEFAULT 'staff',
  status TEXT CHECK (status IN ('active', 'inactive', 'pending')) DEFAULT 'pending',
  avatar_url TEXT,
  last_access TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 3. Voters (Eleitores)
CREATE TABLE IF NOT EXISTS public.voters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cabinet_id UUID REFERENCES public.cabinets(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  cpf TEXT,
  phone TEXT,
  address TEXT,
  city TEXT,
  neighborhood TEXT,
  birth_date DATE,
  category TEXT DEFAULT 'Indeciso',
  status TEXT DEFAULT 'active',
  source TEXT DEFAULT 'Manual',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.voters ENABLE ROW LEVEL SECURITY;

-- 4. Demands (Demandas)
CREATE TABLE IF NOT EXISTS public.demands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cabinet_id UUID REFERENCES public.cabinets(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  beneficiary TEXT,
  author TEXT,
  category TEXT,
  status TEXT DEFAULT 'Pendente',
  priority TEXT DEFAULT 'Média',
  obs TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.demands ENABLE ROW LEVEL SECURITY;

-- 5. Events (Eventos)
CREATE TABLE IF NOT EXISTS public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cabinet_id UUID REFERENCES public.cabinets(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  type TEXT,
  status TEXT,
  date DATE NOT NULL,
  start_time TIME WITHOUT TIME ZONE,
  end_time TIME WITHOUT TIME ZONE,
  location TEXT,
  description TEXT,
  responsible TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

-- 6. Honorees (Homenageados)
CREATE TABLE IF NOT EXISTS public.honorees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cabinet_id UUID REFERENCES public.cabinets(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  social_name TEXT,
  type TEXT,
  ceremony_date TIMESTAMP WITH TIME ZONE,
  justification TEXT,
  bio TEXT,
  status TEXT DEFAULT 'Indicado',
  phone TEXT,
  email TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.honorees ENABLE ROW LEVEL SECURITY;

-- 7. Legislative Projects (Projetos de Lei)
CREATE TABLE IF NOT EXISTS public.legislative_projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cabinet_id UUID REFERENCES public.cabinets(id) ON DELETE CASCADE NOT NULL,
  type TEXT,
  number TEXT NOT NULL,
  year TEXT NOT NULL,
  author TEXT,
  summary TEXT,
  status TEXT DEFAULT 'Em Tramitação',
  document_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.legislative_projects ENABLE ROW LEVEL SECURITY;

-- 8. Notifications (Notificações)
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cabinet_id UUID REFERENCES public.cabinets(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT,
  category TEXT,
  read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;


-- --- POLICIES DE SEGURANÇA (Multi-tenant) ---

-- Função Auxiliar: Verificar o cabinet_id do usuário atual
CREATE OR REPLACE FUNCTION get_user_cabinet_id()
RETURNS UUID AS $$
  SELECT cabinet_id FROM public.profiles WHERE id = auth.uid()
$$ LANGUAGE sql SECURITY DEFINER;

-- 1. Cabinets Policy
-- Usuários podem ver seu próprio gabinete
CREATE POLICY "Users can view own cabinet" ON public.cabinets
FOR SELECT USING (id = get_user_cabinet_id());

-- Usuários podem criar novos gabinetes (Onboarding)
CREATE POLICY "Users can create cabinets" ON public.cabinets
FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- 2. Profiles Policy
-- Usuários podem ver perfis do MESMO gabinete ou se forem eles mesmos
CREATE POLICY "Users can view profiles from same cabinet" ON public.profiles
FOR SELECT USING (
  (cabinet_id = get_user_cabinet_id()) OR (id = auth.uid())
);

-- Usuários podem atualizar seu PRÓPRIO perfil
CREATE POLICY "Users can update own profile" ON public.profiles
FOR UPDATE USING (
  id = auth.uid()
);

-- Usuários podem criar seu PRÓPRIO perfil (Fluxo de Cadastro)
CREATE POLICY "Users can insert own profile" ON public.profiles
FOR INSERT WITH CHECK (auth.uid() = id);

-- 3. Entidades Gerais (Voters, Demands, Events, etc.)
-- Regra: Só pode acessar se o cabinet_id da linha for igual ao cabinet_id do usuário logado

CREATE POLICY "Tenant Isolation: Voters" ON public.voters
FOR ALL USING (cabinet_id = get_user_cabinet_id());

CREATE POLICY "Tenant Isolation: Demands" ON public.demands
FOR ALL USING (cabinet_id = get_user_cabinet_id());

CREATE POLICY "Tenant Isolation: Events" ON public.events
FOR ALL USING (cabinet_id = get_user_cabinet_id());

CREATE POLICY "Tenant Isolation: Honorees" ON public.honorees
FOR ALL USING (cabinet_id = get_user_cabinet_id());

CREATE POLICY "Tenant Isolation: Legislative Projects" ON public.legislative_projects
FOR ALL USING (cabinet_id = get_user_cabinet_id());

CREATE POLICY "Tenant Isolation: Notifications" ON public.notifications
FOR ALL USING (cabinet_id = get_user_cabinet_id());

-- TRIGGER PARA CRIAR PERFIL AUTOMÁTICO (Opcional, mas útil)
-- Cria um perfil quando um usuário se cadastra no Auth, mas sem gabinete definido ainda (será 'null' até ser convidado ou criar um)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, role, status)
  VALUES (new.id, new.raw_user_meta_data->>'name', new.email, 'staff', 'active');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Descomente para ativar o trigger automático no cadastro
-- CREATE TRIGGER on_auth_user_created
--   AFTER INSERT ON auth.users
--   FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
