-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES (Users)
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  role text default 'staff', -- 'admin', 'manager', 'staff', 'volunteer'
  status text default 'active', -- 'active', 'inactive', 'pending'
  avatar_url text,
  last_access timestamp with time zone,
  updated_at timestamp with time zone
);

alter table profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- VOTERS
create table voters (
  id bigint generated by default as identity primary key,
  name text not null,
  cpf text,
  phone text,
  address text,
  city text,
  neighborhood text,
  birth_date date,
  category text, -- 'Liderança', 'Apoiador', 'Voluntário', 'Indeciso'
  status text default 'active', -- 'active', 'inactive'
  source text default 'Manual', -- 'Manual', 'Auto-cadastro', 'Importação'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users -- quem criou
);

alter table voters enable row level security;
create policy "Authenticated users can view voters" on voters for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert voters" on voters for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update voters" on voters for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete voters" on voters for delete using (auth.role() = 'authenticated');

-- DEMANDS
create table demands (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  beneficiary text,
  author text,
  category text, -- 'Infraestrutura', 'Saúde', etc
  status text default 'Pendente', -- 'Pendente', 'Em Andamento', 'Concluída'
  priority text default 'Média', -- 'Alta', 'Média', 'Baixa'
  obs text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  user_id uuid references auth.users -- quem registrou
);

alter table demands enable row level security;
create policy "Authenticated users can view demands" on demands for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert demands" on demands for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update demands" on demands for update using (auth.role() = 'authenticated');

-- EVENTS (Agenda)
create table events (
  id bigint generated by default as identity primary key,
  title text not null,
  type text, -- 'Sessão Ordinária', 'Evento', etc
  status text default 'chegando', -- 'hoje', 'chegando', 'distante', 'concluido'
  date date not null,
  start_time time,
  end_time time,
  location text,
  description text,
  responsible text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table events enable row level security;
create policy "Authenticated users can view events" on events for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert events" on events for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update events" on events for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete events" on events for delete using (auth.role() = 'authenticated');

-- HONOREES
create table honorees (
  id bigint generated by default as identity primary key,
  name text not null,
  social_name text,
  type text, -- 'Titulo de Cidadão...', etc
  ceremony_date date,
  justification text,
  bio text,
  status text default 'Indicado',
  phone text,
  email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table honorees enable row level security;
create policy "Authenticated users can view honorees" on honorees for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert honorees" on honorees for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update honorees" on honorees for update using (auth.role() = 'authenticated');

-- LEGISLATIVE PROJECTS
create table legislative_projects (
  id bigint generated by default as identity primary key,
  type text, -- 'Projeto de Lei', etc
  number text,
  year text,
  author text,
  summary text,
  status text default 'Em Tramitação', -- 'Finalizado', 'Em Tramitação', 'Arquivado'
  document_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table legislative_projects enable row level security;
create policy "Authenticated users can view projects" on legislative_projects for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert projects" on legislative_projects for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update projects" on legislative_projects for update using (auth.role() = 'authenticated');

-- NOTIFICATIONS
create table notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  message text,
  type text default 'info',
  category text default 'system',
  read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users
);

alter table notifications enable row level security;
create policy "Users can view own notifications" on notifications for select using (auth.uid() = user_id);
