-- Create the new table for Legislative Projects (formerly legislative_matters)
-- This table avoids conflicts with the 'legislative_matters' bucket/folder.

CREATE TABLE IF NOT EXISTS public.legislative_projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cabinet_id UUID REFERENCES public.cabinets(id) ON DELETE CASCADE NOT NULL,
  type_description TEXT NOT NULL, -- Ex: "Projeto de Lei", "Requerimento"
  type_acronym TEXT, -- Ex: "PL", "REQ"
  number INTEGER,
  year INTEGER NOT NULL,
  authors TEXT, -- Ex: "Vereador X"
  description TEXT, -- Ementa/Resumo
  status TEXT DEFAULT 'Em Tramitação', -- "Em Tramitação", "Aprovado", "Arquivado"
  pdf_url TEXT, -- Link to the original document (migrated or new)
  external_id TEXT, -- Legacy ID if imported
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Index for faster filtering
CREATE INDEX IF NOT EXISTS idx_legislative_projects_cabinet ON public.legislative_projects(cabinet_id);
CREATE INDEX IF NOT EXISTS idx_legislative_projects_status ON public.legislative_projects(status);

-- 1. Enable RLS
ALTER TABLE public.legislative_projects ENABLE ROW LEVEL SECURITY;

-- 2. Create RLS Policies
-- Policy: Tenant Isolation (Users can only see/edit projects from their own cabinet)

-- SELECT (Read)
DROP POLICY IF EXISTS "Tenant Isolation: Select Projects" ON public.legislative_projects;
CREATE POLICY "Tenant Isolation: Select Projects" 
ON public.legislative_projects 
FOR SELECT 
USING (
  cabinet_id = get_user_cabinet_id()
);

-- INSERT (Create)
DROP POLICY IF EXISTS "Tenant Isolation: Insert Projects" ON public.legislative_projects;
CREATE POLICY "Tenant Isolation: Insert Projects" 
ON public.legislative_projects 
FOR INSERT 
WITH CHECK (
  cabinet_id = get_user_cabinet_id()
);

-- UPDATE (Edit)
DROP POLICY IF EXISTS "Tenant Isolation: Update Projects" ON public.legislative_projects;
CREATE POLICY "Tenant Isolation: Update Projects" 
ON public.legislative_projects 
FOR UPDATE 
USING (
  cabinet_id = get_user_cabinet_id()
);

-- DELETE (Remove)
DROP POLICY IF EXISTS "Tenant Isolation: Delete Projects" ON public.legislative_projects;
CREATE POLICY "Tenant Isolation: Delete Projects" 
ON public.legislative_projects 
FOR DELETE 
USING (
  cabinet_id = get_user_cabinet_id()
);

-- Grant permissions to authenticated users
GRANT ALL ON public.legislative_projects TO authenticated;
GRANT ALL ON public.legislative_projects TO service_role;
