-- Criação da tabela de Ofícios (Espaço Legislativo)
CREATE TABLE IF NOT EXISTS public.offices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cabinet_id UUID REFERENCES public.cabinets(id) ON DELETE CASCADE NOT NULL,
  number TEXT NOT NULL,
  year TEXT NOT NULL,
  recipient TEXT, -- Destinatário (ex: Prefeito, Secretário)
  subject TEXT, -- Assunto
  status TEXT DEFAULT 'Pendente', -- Pendente, Enviado, Respondido
  document_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.offices ENABLE ROW LEVEL SECURITY;

-- Policies para Offices
CREATE POLICY "Tenant Isolation: Offices" ON public.offices
FOR ALL USING (cabinet_id = get_user_cabinet_id());

-- Grant permissions (if needed, usually authenticated role covers it)
GRANT ALL ON public.offices TO authenticated;
GRANT ALL ON public.offices TO service_role;
